### ISSUE TITLE
Where is the witx generation code?

### ISSUE THREAD

**Issue by willemneal** [jedisct1/zigly#2]
I noticed this comment in the `wasm.zig` file:

```
//// This file was automatically generated by witx-codegen - Do not edit manually.//
```

Yet I can't find the code that does this.

**Comment by jedisct1** [comment]
Hi Willem!

It's generated by [witx-codegen](https://github.com/jedisct1/witx-codegen).

**Comment by willemneal** [comment]
Awesome thanks!
