### ISSUE TITLE
CacheOverrideTag has off-by-one error due to mistake in Compute@Edge witx

### ISSUE THREAD

**Issue by joeshaw** [jedisct1/zigly#3]
https://github.com/fastly/Viceroy/pull/269 fixed a bug in the definition for the cache override tag flags.  In short, it erroneously listed `$none` as a flag.  In witx, flags start at 1, not 0.  As a result, all the values for `CacheOverrideTag` are off by one:

```zig
/// An override for response caching behavior.
pub const CacheOverrideTag = u32;
pub const CACHE_OVERRIDE_TAG_NONE: CacheOverrideTag = 0x1;
pub const CACHE_OVERRIDE_TAG_PASS: CacheOverrideTag = 0x2;
pub const CACHE_OVERRIDE_TAG_TTL: CacheOverrideTag = 0x4;
pub const CACHE_OVERRIDE_TAG_STALE_WHILE_REVALIDATE: CacheOverrideTag = 0x8;
pub const CACHE_OVERRIDE_TAG_PCI: CacheOverrideTag = 0x10;
```

Regenerating based on the updated witx should fix this.

**Comment by jedisct1** [comment]
Thank you!

https://github.com/jedisct1/zigly/commit/163e200561f382f2796207c09ccfd7ab00eb8225 updates all this, but there's now quite a lot of new functions that we need to support :)
